### ISSUE TITLE
Add option: actual file modification dates

### ISSUE THREAD

**Issue by f2d** [evanmiller/mod_zip#63] opened 2018-01-17 15:57 UTC
Please add support for giving actual file modification dates inside zip.
Possibly as an option in config:
- None (default, give request date).
- From text file list content (I have the dates already in DB for other purposes, so I'd prefer this).
- From filesystem, text file list's own last-mod.date.
- From filesystem, each file's own.

**Comment by evanmiller** [comment] 2020-10-25 17:17
Duplicate of #74

**Closed by evanmiller** 2020-10-25 17:17 UTC
